### ISSUE TITLE
Error when using `TaskLoader.load_dask()` when `aux_at_contexts` is `None`

### ISSUE THREAD

**Issue by magnusross** [tom-andersson/deepsensor#45] opened 2023-09-01 10:05 UTC
Hi, I think there is a very small issue in the `TaskLoader.load_dask()` function, introduced in the new version, when `aux_at_contexts=None`, which is the default. 

If you run the function you get `TypeError: 'NoneType' object is not subscriptable`. I think it is caused by the index in this line:
https://github.com/tom-andersson/deepsensor/blob/af06462953535156984df63e09016905a1a91eaa/deepsensor/data/loader.py#L186

It seems to work if changed to `load(self.aux_at_contexts)` so maybe just a typo? Can make a PR if needed, cheers!

**Comment by tom-andersson** [comment] 2023-09-04 11:19
Thanks for catching this, @magnusross! This is now fixed with version `0.1.9` on pip. Explanation below.

The root cause of this was a silly design choice for `aux_at_contexts`, where it was a 2-tuple containing: an integer context set index to sample the gridded auxiliary data at, and the xarray gridded auxiliary object. The auxiliary data would then be sampled at the other context set's locations and appended as the final context set. The main use case is to provide the `ConvNP` with high-resolution auxiliary information at in-situ, off-grid station locations. Then, hypothetically, with the right auxiliary information and enough data, the model can distinguish between an observation from the top of a mountain vs a plain vs in a city.

In https://github.com/tom-andersson/deepsensor/commit/2fc1662e24f24b93914386a90901e4dd733fcf17, I've re-designed `aux_at_contexts` to be a single xarray object, which is automatically sampled at all the non-gridded context sets. This is simpler and leads to less bug-prone bespoke code. A new unit test for `TaskLoader.load_dask` (https://github.com/tom-andersson/deepsensor/commit/23e055b62a21f05559d540f00bcf68d4c8de6412) is passing on `main`.

**Closed by tom-andersson** 2023-09-04 11:19 UTC

**Comment by tom-andersson** [comment] 2023-09-04 11:30
FYI here are the latest docs on `aux_at_contexts` and `aux_at_targets`: https://github.com/tom-andersson/deepsensor/blob/c85bd53b00771b676e4e34f9aca50e34bb68e834/deepsensor/data/loader.py#L47-L54
